### ISSUE TITLE
Return momenta before calling computation

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/sot-dynamic-pinocchio#44]
https://github.com/stack-of-tasks/sot-dynamic-pinocchio/blob/9c7ae90f80e59747b76f258550c2facbb2d51077/src/sot-dynamic-pinocchio.cpp#L976

**Comment by olivier-stasse** [comment]
Thanks Gabriele to point this out.
Will try to integrate it in the next release.
Sorry for delay.

**Comment by olivier-stasse** [comment]
Fixed by #47
