### ISSUE TITLE
Unable to run locally compiled code

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/sot-dynamic-pinocchio#58]
When building sot-dynamic-pinocchio from source and installing it with prefix `/opt/openrobots`, my python code is not able to find all the required libraries.

Does the installation expect libraries to be versioned? Is there a way to achieve this when I install a self-build version?

**Comment by jmirabel** [comment]
Could you give some precision please :
- did you uninstall robotpkg-sot-dynamic-pinicchio-v3 ?
- was the Python code installed in the right place (dist-packages vs site-packages) ?
- what does ldd says ?

**Comment by nim65s** [comment]
Do you mean the .so libraries that are in `lib/`, or the python modules (folders / .py / .so) that are in `lib/python*/*-packages/` ?

For use with `/opt/openrobots`, we usually set `-DPYTHON_STANDARD_LAYOUT=ON`, and you can compare the layout of your source installation with the layout of the binary package if needed.

**Comment by jviereck** [comment]
Hi, thanks for the input! Let me try the `-DPYTHON_STANDARD_LAYOUT=ON` and get back to you.

**Comment by olivier-stasse** [comment]
@jviereck can we close the issue ?
