### ISSUE TITLE
Double __init__.py

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/sot-dynamic-pinocchio#73]
Hi @nim65s 

In 62982b5, you added the installation of a second __init__.py file, together with some python files related to romeo. The __init__.py file overwrites the one installed by src/CMakeLists.txt.

Is this on purpose ? If yes, I should remove src/dynamic_graph/.../__init__.py. If no, which one should we remove ?

**Comment by nim65s** [comment]
I can only find one `__init__.py` file in this repo: https://github.com/stack-of-tasks/sot-dynamic-pinocchio/blob/devel/src/dynamic_graph/sot/dynamic_pinocchio/__init__.py 

This is the one referenced here: https://github.com/stack-of-tasks/sot-dynamic-pinocchio/blob/devel/src/CMakeLists.txt#L49

Which is the other one ?

**Comment by jmirabel** [comment]
My local repo was not up-to-date. f2a0510 fixed it.
