### ISSUE TITLE
Bug in `DynamicPinocchio::computeJacobians`

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/sot-dynamic-pinocchio#75]
Hi there,

looking at the change in https://github.com/stack-of-tasks/sot-dynamic-pinocchio/commit/b4ff11993ebfc74162a1adfdd5240509b16e7ba4#diff-831036c6c653e73bea0ed8671360385bR671

it looks like the 

```
pinocchio::JointIndex id = isFrame
    ? m_model->frames[(pinocchio::JointIndex)jointId].parent
    : (pinocchio::JointIndex)jointId;
```

is wrong. Reading the old code, I think the two lines should be swapped:

```
pinocchio::JointIndex id = isFrame
    ? (pinocchio::JointIndex)jointId
    : m_model->frames[(pinocchio::JointIndex)jointId].parent;
```

What do you think?

**Comment by olivier-stasse** [comment]
Dear @jviereck,
I believe that the change is correct as you may have a Frame expressed in the reference frame of a joint. It goes with the notion of operational points which is rigidly fixed to a joint. This is the case for sensor frame. 

In this case, the frame has an index in the model, but the computation are done with respect to the index of the joint with which it is linked.

**Comment by jviereck** [comment]
Thanks for looking into this @olivier-stasse . I think you are right. I am closing the issue. Sorry for making noise.

**Comment by olivier-stasse** [comment]
No problem, we have a hugh documentation debt regarding this kind of concept. Thanks for looking into the code.
