### ISSUE TITLE
[CMake] lapack link fail on buster

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-dynamic-pinocchio#82]
From CI in #81 https://gitlab.laas.fr/stack-of-tasks/sot-dynamic-pinocchio/-/jobs/91082 : 

```
/usr/bin/ld: cannot find -llapack
collect2: error: ld returned 1 exit status
```

**Comment by olivier-stasse** [comment]
I am looking into it.

**Comment by olivier-stasse** [comment]
I was able to compile the package without LAPACK.
On the down side, this package does not have enough unit tests...

**Comment by olivier-stasse** [comment]
Sorry after a deeper review LAPACK is necessary for integrator-force-exact:
https://github.com/stack-of-tasks/sot-dynamic-pinocchio/blob/7d1fbf6022f239b06e5f1a2b30a326ebb91a9e41/src/integrator-force-exact.cpp#L60 is calling explicitely dgeev_

**Comment by nim65s** [comment]
Ok, thanks. Then https://gitlab.laas.fr/gepetto/buildfarm/-/commit/c9a2a4191c3569eb7a587640bdf91882c94f989f will fix this issue.
